version: "2"

linters:
  default: standard
  enable:
    - errorlint      # proper error wrapping/comparison
    - gocritic       # opinionated style checks
    - misspell       # catch typos in comments/strings
    - unconvert      # unnecessary type conversions
    - unparam        # unused function parameters
    - usestdlibvars  # use stdlib constants (http.MethodGet, etc.)
    - whitespace     # unnecessary blank lines
  settings:
    gocritic:
      enabled-tags:
        - diagnostic
        - style
      disabled-checks: []

formatters:
  enable:
    - gofmt

issues:
  max-issues-per-linter: 50
  max-same-issues: 5
